In [355]:
import requests
from bs4 import BeautifulSoup
import json
import pandas as pd
import time
import numpy as np
from datetime import datetime
import yfinance as yf
import os
import glob
import regex as re
import csv
import statistics

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
import matplotlib.pyplot as plt

from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [357]:
def remove_none_types(mydf):
    if mydf.isnull().values.any():
        return False
    else:
        return True

X_data = []
Y_data = []

sectors = ["automobiles", "banks"]
for sector in sectors:
    filelist = os.listdir("sectors/"+sector)
    try:
        filelist.remove('.DS_Store')
    except:
        pass

    for stock in filelist:
        sector_files = glob.glob('sectors/'+str(sector)+'/'+str(stock)+'/'+str(stock)+'20*[0-9]**[0-9]*[1-4].*')
        sector_files.sort(reverse=True)

        testpath = sector_files[0]
        testdata_from_csv = pd.read_csv(testpath)
        try:
            market_cap = float(testdata_from_csv.iloc[[-1]].values[0][0])
            if (market_cap > 500000000):
                number_to_loop = len(sector_files)
                if number_to_loop%3 != 0:
                    number_to_loop = number_to_loop-(number_to_loop%3) #gets nearest (inclusive) multiples of 3
                for i in range(0, number_to_loop+2, 3): # for every .csv path of that stock
                    path = sector_files[i]
                    path2 = sector_files[i+1]
                    path3 = sector_files[i+2]
                    data_from_csv = pd.read_csv(path)
                    data_from_csv2 = pd.read_csv(path2)
                    data_from_csv3 = pd.read_csv(path3)
                    Checks_None = remove_none_types(data_from_csv)
                    Checks_None2 = remove_none_types(data_from_csv2)
                    Checks_None3 = remove_none_types(data_from_csv3)
                    if (Checks_None == True) and (Checks_None2 == True) and (Checks_None3 == True):
                        single_X_data = (np.array((data_from_csv[3:85].astype(float))).flatten()) 
                        single_X_data2 = (np.array((data_from_csv2[3:85].astype(float))).flatten()) 
                        single_X_data3 = (np.array((data_from_csv3[3:85].astype(float))).flatten()) 
                        if ((single_X_data.shape[0]) == 82) and ((single_X_data2.shape[0]) == 82) and ((single_X_data3.shape[0]) == 82):
                            X_data.append(single_X_data)
                            X_data.append(single_X_data2)
                            X_data.append(single_X_data3)
                            single_Y_data = np.array(data_from_csv[85:95].astype(float)).flatten()
                            Y_data.append(single_Y_data)
        except:
            pass


                

#[
#   [#AAPL
#       [ [earnings call 1], [earnings call 2], [earnings call 3]
#   ],
#   [#MSFT
#       [ [earnings call 1], [earnings call 2], [earnings call 3]
#   ]
#
# ]



ORI_X_data = np.array(X_data)

ORI_Y_data = np.array(Y_data)
# ORI_Y_data = ORI_Y_data[:,:5]



In [383]:
def remove_none_types(mydf):
    if mydf.isnull().values.any():
        return False
    else:
        return True

X_data = []
Y_data = []

sectors = ["automobiles", "banks"]
for sector in sectors:
    filelist = os.listdir("sectors/"+sector)
    try:
        filelist.remove('.DS_Store')
    except:
        pass

    for stock in filelist:
        sector_files = glob.glob('sectors/'+str(sector)+'/'+str(stock)+'/'+str(stock)+'20*[0-9]**[0-9]*[1-4].*')
        sector_files.sort(reverse=True)

        testpath = sector_files[0]
        testdata_from_csv = pd.read_csv(testpath)
        try:
            market_cap = float(testdata_from_csv.iloc[[-1]].values[0][0])
            if (market_cap > 5000000000):
                number_to_loop = len(sector_files)
                if number_to_loop%2 != 0:
                    number_to_loop = number_to_loop-(number_to_loop%2) 
                for i in range(0, number_to_loop+1, 2): # for every .csv path of that stock
                    path = sector_files[i]
                    path2 = sector_files[i+1]
                    data_from_csv = pd.read_csv(path)
                    data_from_csv2 = pd.read_csv(path2)
                    Checks_None = remove_none_types(data_from_csv)
                    Checks_None2 = remove_none_types(data_from_csv2)
                    if (Checks_None == True) and (Checks_None2 == True):
                        single_X_data = (np.array((data_from_csv[3:85].astype(float))).flatten()) 
                        single_X_data2 = (np.array((data_from_csv2[3:85].astype(float))).flatten()) 
                        if ((single_X_data.shape[0]) == 82) and ((single_X_data2.shape[0]) == 82):
                            X_data.append(single_X_data)
                            X_data.append(single_X_data2)
                            single_Y_data = np.array(data_from_csv[85:95].astype(float)).flatten()
                            Y_data.append(single_Y_data)
        except:
            pass


                

#[
#   [#AAPL
#       [ [earnings call 1], [earnings call 2], [earnings call 3]
#   ],
#   [#MSFT
#       [ [earnings call 1], [earnings call 2], [earnings call 3]
#   ]
#
# ]



ORI_X_data = np.array(X_data)

ORI_Y_data = np.array(Y_data)
# ORI_Y_data = ORI_Y_data[:,:5]



In [384]:
scaler = StandardScaler()
X_data = scaler.fit_transform(ORI_X_data)
X_data

array([[ 0.05746078,  1.61578883,  1.19836207, ...,  0.18097152,
         0.97246949,  0.17851685],
       [-0.00547779,  1.27385356,  1.73668944, ...,  0.73719168,
        -0.71082599, -0.03991479],
       [ 0.03978639,  1.04040048,  0.97985731, ..., -0.26304118,
         0.72942698,  1.22779005],
       ...,
       [ 0.0239148 ,  0.12939548,  0.47761612, ...,  0.76529605,
         0.96407242,  0.95758538],
       [ 0.09939671,  0.33414797,  0.48577949, ...,  1.70478436,
         1.08904976,  0.31056905],
       [ 0.02159196,  0.73154351,  1.11011976, ...,  1.07723495,
         0.12043322,  1.63181319]])

In [385]:
X_data = X_data.reshape(-1,2,82)

In [386]:
Y_data = ORI_Y_data.reshape(-1,10)
Y_data

array([[ 0.18715475,  0.11144807, -0.00389906, ..., -0.02821215,
         0.05969993,  0.16895602],
       [-0.11340496,  0.01913649, -0.14375942, ..., -0.13056379,
        -0.16138605,  0.00708335],
       [-0.05403898, -0.07270197, -0.09632308, ..., -0.09712789,
        -0.09952134, -0.23015699],
       ...,
       [ 0.03036057,  0.08349139,  0.12142812, ...,  0.08838353,
         0.05637264, -0.04335492],
       [ 0.00063696,  0.05286605,  0.06496794, ...,  0.0690536 ,
         0.12612933,  0.08829283],
       [ 0.0246459 ,  0.06531101,  0.05668503, ...,  0.09865488,
         0.14555631,  0.09351488]])

In [387]:
Y_data = Y_data[:,:5]
Y_data

array([[ 0.18715475,  0.11144807, -0.00389906,  0.08621249,  0.19820205],
       [-0.11340496,  0.01913649, -0.14375942, -0.17411388, -0.00820138],
       [-0.05403898, -0.07270197, -0.09632308, -0.09871867, -0.22947077],
       ...,
       [ 0.03036057,  0.08349139,  0.12142812,  0.08844501, -0.01431067],
       [ 0.00063696,  0.05286605,  0.06496794,  0.12182607,  0.08413365],
       [ 0.0246459 ,  0.06531101,  0.05668503,  0.10179527,  0.05174122]])

In [388]:
X_data[0:2]

array([[[ 0.05746078,  1.61578883,  1.19836207, -0.94898107,
         -1.7928399 , -0.43349364, -0.34921608,  0.36061076,
         -0.9799415 ,  0.04178318, -0.65343353, -0.68321556,
         -0.78907642,  1.88950502,  1.44990238, -1.07781823,
         -2.48825064,  0.40898008, -0.38844046, -1.09370378,
         -0.45283743,  1.42538434,  0.54283879, -1.06638608,
          0.02918357,  1.81081021,  0.9372234 ,  0.90189923,
          0.90652208, -0.23034271, -1.0792426 , -0.12845517,
         -0.66158995, -0.89173257, -0.95332343, -1.23395959,
          0.59529097,  1.16821967,  1.28754962, -0.20256845,
         -0.44954612, -0.06943422,  0.95426796,  1.08577778,
          1.17066863, -0.34951063,  0.71465049,  0.56516673,
         -0.59115395,  0.01474719, -0.52396011, -0.9403486 ,
         -0.28894902, -0.04152869,  0.70111423, -0.51731615,
          0.3053057 ,  0.        ,  1.31697272,  1.67113009,
         -0.29380625, -0.51080982,  0.28828981,  1.81676084,
          0.62616457,  0

In [389]:
X_data.shape

(423, 2, 82)

In [390]:
Y_data.shape

(423, 5)

In [396]:
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size=0.42, random_state=42)
Y_train.shape

(245, 5)

In [296]:
# model2 = model

In [392]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Bidirectional, Dropout, TimeDistributed
from keras.optimizers import Adam
# Generate toy data for demonstration purposes
timesteps = 2
input_dim = 82
num_classes = len(np.unique(Y_train))


model = Sequential()
model.add(LSTM(82, input_shape=(timesteps,input_dim), return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(64, input_shape=(timesteps,input_dim), return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(32, return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(16, return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(8, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax'))
optimizer = Adam(lr=0.001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, epochs=200, batch_size=30, validation_split=0.4)


Epoch 1/200


/Users/victor/miniforge3/envs/NLP_env/lib/python3.8/site-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
2023-02-08 09:11:45.867352: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:46.629127: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:47.302197: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:47.720318: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:48.079529: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabl

5/5 [==============================] - ETA: 0s - loss: 0.2534 - accuracy: 0.2585

2023-02-08 09:11:57.768440: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:58.055471: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:58.324862: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:58.586034: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:58.884411: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-02-08 09:11:59.159482: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


5/5 [==============================] - 19s 2s/step - loss: 0.2534 - accuracy: 0.2585 - val_loss: 0.3186 - val_accuracy: 0.1939
Epoch 2/200
5/5 [==============================] - 4s 773ms/step - loss: 0.2533 - accuracy: 0.2721 - val_loss: 0.3185 - val_accuracy: 0.2041
Epoch 3/200
5/5 [==============================] - 2s 515ms/step - loss: 0.2533 - accuracy: 0.2517 - val_loss: 0.3185 - val_accuracy: 0.2143
Epoch 4/200
5/5 [==============================] - 1s 217ms/step - loss: 0.2530 - accuracy: 0.2857 - val_loss: 0.3184 - val_accuracy: 0.2245
Epoch 5/200
5/5 [==============================] - 1s 242ms/step - loss: 0.2528 - accuracy: 0.2925 - val_loss: 0.3183 - val_accuracy: 0.2449
Epoch 6/200
5/5 [==============================] - 1s 145ms/step - loss: 0.2532 - accuracy: 0.2721 - val_loss: 0.3183 - val_accuracy: 0.2755
Epoch 7/200
5/5 [==============================] - 1s 156ms/step - loss: 0.2528 - accuracy: 0.2653 - val_loss: 0.3182 - val_accuracy: 0.2449
Epoch 8/200
5/5 [==========

In [401]:
Y_pred = model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)
print(f'MSE: {mse:.2f}')
print(f'R2: {r2:.2f}')

plt.figure(figsize=(10,10))
plt.scatter(Y_pred, Y_test)
plt.ylabel("Actual Stock Returns")
plt.xlabel("Predicted Stock Returns")
plt.title("Predicted vs Actual Stock Returns")
plt.show()

In [381]:
Y_pred[0:5]

array([[0.1758499 , 0.1115374 , 0.11806431, 0.35915485, 0.23539351],
       [0.14748642, 0.32831475, 0.3417308 , 0.0678051 , 0.114663  ],
       [0.17585044, 0.11153541, 0.11806197, 0.35916072, 0.23539153],
       [0.1758501 , 0.11153518, 0.11806197, 0.35916072, 0.23539197],
       [0.17584987, 0.11153525, 0.11806183, 0.35916096, 0.23539214]],
      dtype=float32)

In [382]:
Y_test[0:5]

array([[-0.08045977, -0.13218381, -0.09578568, -0.13601514, -0.58045981],
       [-0.03092562, -0.00497413, -0.0341696 , -0.020545  , -0.00700478],
       [-0.0061308 , -0.01426791, -0.08781975, -0.07338441, -0.05344972],
       [ 0.06046141,  0.05724236,  0.05042499, -0.08421559, -0.08364814],
       [-0.03031538,  0.02369234,  0.11084151,  0.09242959,  0.06174332]])